"""add_status_display_name_to_devices

Revision ID: 0f10bde0bcbd
Revises: f72cb8a898ee
Create Date: 2026-05-02 12:37:03.213967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f10bde0bcbd'
down_revision: Union[str, Sequence[str], None] = 'f72cb8a898ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('display_name', sa.String(length=100), nullable=True))
    op.add_column('devices', sa.Column('status', sa.String(length=20), nullable=True))
    op.execute("UPDATE devices SET status = 'active'")
    op.alter_column('devices', 'status', nullable=False)
    op.alter_column('devices', 'device_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_index(op.f('ix_devices_device_name'), 'devices', ['device_name'], unique=False)
    op.drop_column('devices', 'jwt_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('jwt_token', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_devices_device_name'), table_name='devices')
    op.alter_column('devices', 'device_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('devices', 'status')
    op.drop_column('devices', 'display_name')
    # ### end Alembic commands ###
