"""add_is_archived_to_support_tickets

Revision ID: 8933ccbddaf5
Revises: 153bf688e743
Create Date: 2026-04-19 10:47:58.080318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8933ccbddaf5'
down_revision: Union[str, Sequence[str], None] = '153bf688e743'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_tickets', sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('support_tickets', 'is_archived')
    # ### end Alembic commands ###
