"""users tablosundan phone gender avatar_url kaldirildi

Revision ID: ad5b4cfda3e5
Revises: a5c2e8f1b3d9
Create Date: 2026-06-08 18:06:05.493611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad5b4cfda3e5'
down_revision: Union[str, Sequence[str], None] = 'a5c2e8f1b3d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('gender', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    # ### end Alembic commands ###
