"""vault_item_url

Revision ID: f72cb8a898ee
Revises: 8933ccbddaf5
Create Date: 2026-04-26 17:19:11.660622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f72cb8a898ee'
down_revision: Union[str, Sequence[str], None] = '8933ccbddaf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vault_items', sa.Column('url', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vault_items', 'url')
    # ### end Alembic commands ###
